spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/backend
    username: "example_username"
    password: "example_password"
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB

app:
  token:
    secret: "example_secret"
    issuer: "example_issuer"

# Path: src/main/resources/application.yaml