spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: oatwant43
    password: unojvpsikiwkfsrw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/backend
    username: postgres
    password: syspass
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB

app:
  token:
    secret: "#gYWe34IZaB55NHAuEjNlJtR0u2bYsqspODvvqdpp2r9nkDCCYxj9S3jI0Rm5fyv"
    issuer: BackendService
  email:
    from: oatwant43@gmail.com


# Path: src/main/resources/application.yaml